# Callback data
CALLBACK_DATA_UZ = "UZ"
CALLBACK_DATA_RU = "RU"

CALLBACK_DATA_GIVE_QUESTION = "give_question"
CALLBACK_DATA_ADD_ADVERTISEMENT = "give_advertisement"
CALLBACK_DATA_ADD_PHOTOS = "ADD_PHOTOS"

CALLBACK_DATA_ECONOMIC = "ECONOMIC"
CALLBACK_DATA_STANDARD = "STANDARD"
CALLBACK_DATA_PREMIUM = "PREMIUM"
CALLBACK_DATA_ELITE = "ELITE"
CALLBACK_DATA_EXCLUSIVE = "EXCLUSIVE"
CALLBACK_DATA_EXTREME = "EXTREME"

CALLBACK_DATA_BODY_TYPE_SEDAN = "BODY_TYPE_SEDAN"
CALLBACK_DATA_BODY_TYPE_COUPE = "BODY_TYPE_COUPE"
CALLBACK_DATA_BODY_TYPE_HATCHBACK = "BODY_TYPE_HATCHBACK"
CALLBACK_DATA_BODY_TYPE_UNIVERSAL = "BODY_TYPE_UNIVERSAL"
CALLBACK_DATA_BODY_TYPE_CROSSOVER = "BODY_TYPE_CROSSOVER"
CALLBACK_DATA_BODY_TYPE_SUV = "BODY_TYPE_SUV"
CALLBACK_DATA_BODY_TYPE_OTHER = "BODY_TYPE_OTHER"

# GEARBOX TYPE
CALLBACK_DATA_GEARBOX_TYPE_AUTOMATIC = "GEARBOX_TYPE_AUTOMATIC"
CALLBACK_DATA_GEARBOX_TYPE_MECHANICAL = "GEARBOX_TYPE_MECHANICAL"
CALLBACK_DATA_GEARBOX_TYPE_OTHER = "GEARBOX_TYPE_OTHER"

CALLBACK_DATA_CLICK = "CLICK"
CALLBACK_DATA_PAYME = "PAYME"

# CLICK ERROR CODES
CLICK_SUCCESS = 0
CLICK_INCORRECT_SIGN_CHECK = -1
CLICK_INCORRECT_AMOUNT = -2
CLICK_ACTION_NOT_FOUND = -3
CLICK_ALREADY_PAID = -4
CLICK_USER_DOES_NOT_EXIST = -5
CLICK_TRANSACTION_DOES_NOT_EXIST = -6
CLICK_FAILED_TO_UPDATE_USER = -7
CLICK_ERROR_FROM_CLICK = -8
CLICK_TRANSACTION_CANCELLED = -9

PAYME_ERROR_INTERNAL_SYSTEM = -32400
PAYME_ERROR_INSUFFICIENT_PRIVILEGE = -32504
PAYME_ERROR_INVALID_JSON_RPC_OBJECT = -32600
PAYME_ERROR_METHOD_NOT_FOUND = -32601
PAYME_ERROR_INVALID_AMOUNT = -31001
PAYME_ERROR_ORDER_NOT_FOUND = -31098
PAYME_ERROR_INVALID_ACCOUNT = -31050
PAYME_ERROR_COULD_NOT_CANCEL = -31007
PAYME_ERROR_TRANSACTION_NOT_FOUND = -31003
PAYME_ERROR_COULD_NOT_PERFORM = -31008

# COLOR
CALLBACK_DATA_COLOR_BLACK = "COLOR_BLACK"
CALLBACK_DATA_COLOR_WHITE = "COLOR_WHITE"
CALLBACK_DATA_COLOR_GREY = "GREY"
CALLBACK_DATA_COLOR_CYAN = "COLOR_CYAN"
CALLBACK_DATA_COLOR_RED = "COLOR_RED"
CALLBACK_DATA_COLOR_BLUE = "COLOR_BLUE"
CALLBACK_DATA_COLOR_BEIGE = "COLOR_BEIGE"
CALLBACK_DATA_COLOR_SILVER = "COLOR_SILVER"
CALLBACK_DATA_COLOR_GREEN = "COLOR_GREEN"
CALLBACK_DATA_COLOR_BROWN = "COLOR_BROWN"
CALLBACK_DATA_COLOR_OTHER = "COLOR_OTHER"

# FUEL TYPE
CALLBACK_DATA_FUEL_TYPE_PETROL = "FUEL_TYPE_PETROL"
CALLBACK_DATA_FUEL_TYPE_GAS = "FUEL_TYPE_GAS"
CALLBACK_DATA_FUEL_TYPE_ELECTRO = "FUEL_TYPE_ELECTRO"
CALLBACK_DATA_FUEL_TYPE_HYBRID = "FUEL_TYPE_HYBRID"
CALLBACK_DATA_FUEL_TYPE_PETROL_GAS = "FUEL_TYPE_PETROL_GAS"

# MACHINE CONDITION
CALLBACK_DATA_MACHINE_CONDITION_EXCELLENT = "MACHINE_CONDITION_EXCELLENT"
CALLBACK_DATA_MACHINE_CONDITION_GOOD = "MACHINE_CONDITION_GOOD"
CALLBACK_DATA_MACHINE_CONDITION_AVERAGE = "MACHINE_CONDITION_AVERAGE"
CALLBACK_DATA_MACHINE_CONDITION_NEEDS_REPAIR = "MACHINE_CONDITION_NEEDS_REPAIR"

# NUMBER OF OWNERS
CALLBACK_DATA_NUMBER_OF_OWNERS_1 = "NUMBER_OF_OWNERS_1"
CALLBACK_DATA_NUMBER_OF_OWNERS_2 = "NUMBER_OF_OWNERS_2"
CALLBACK_DATA_NUMBER_OF_OWNERS_3 = "NUMBER_OF_OWNERS_3"
CALLBACK_DATA_NUMBER_OF_OWNERS_OTHER = "NUMBER_OF_OWNERS_OTHER"

# CITY
CALLBACK_DATA_CITY_TASHKENT = "CITY_TASHKENT"
CALLBACK_DATA_CITY_SAMARKAND = "CITY_SAMARKAND"
CALLBACK_DATA_CITY_ANDIJAN = "CITY_ANDIJAN"
CALLBACK_DATA_CITY_FERGANA = "CITY_FERGANA"
CALLBACK_DATA_CITY_BUKHARA = "CITY_BUKHARA"
CALLBACK_DATA_CITY_OTHER = "CITY_OTHER"

# PAYMENT TYPE
CALLBACK_DATA_PAYMENT_TYPE_CASH = "PAYMENT_TYPE_CASH"
CALLBACK_DATA_PAYMENT_TYPE_LEASING = "PAYMENT_TYPE_LEASING"
CALLBACK_DATA_PAYMENT_TYPE_TRANSFER = "PAYMENT_TYPE_TRANSFER"
CALLBACK_DATA_PAYMENT_TYPE_CREDIT = "PAYMENT_TYPE_CREDIT"
CALLBACK_DATA_PAYMENT_TYPE_INSTALLMENT = "PAYMENT_TYPE_INSTALLMENT"