# Callback data
CALLBACK_DATA_UZ = "UZ"
CALLBACK_DATA_RU = "RU"

CALLBACK_DATA_GIVE_QUESTION = "give_question"
CALLBACK_DATA_ADD_ADVERTISEMENT = "give_advertisement"
CALLBACK_DATA_ADD_PHOTOS = "ADD_PHOTOS"

CALLBACK_DATA_ECONOMIC = "ECONOMIC"
CALLBACK_DATA_STANDARD = "STANDARD"
CALLBACK_DATA_PREMIUM = "PREMIUM"
CALLBACK_DATA_ELITE = "ELITE"
CALLBACK_DATA_EXCLUSIVE = "EXCLUSIVE"
CALLBACK_DATA_EXTREME = "EXTREME"

CALLBACK_DATA_CLICK = "CLICK"
CALLBACK_DATA_PAYME = "PAYME"

# CLICK ERROR CODES
CLICK_SUCCESS = 0
CLICK_INCORRECT_SIGN_CHECK = -1
CLICK_INCORRECT_AMOUNT = -2
CLICK_ACTION_NOT_FOUND = -3
CLICK_ALREADY_PAID = -4
CLICK_USER_DOES_NOT_EXIST = -5
CLICK_TRANSACTION_DOES_NOT_EXIST = -6
CLICK_FAILED_TO_UPDATE_USER = -7
CLICK_ERROR_FROM_CLICK = -8
CLICK_TRANSACTION_CANCELLED = -9
