# Callback data
CALLBACK_DATA_UZ = "UZ"
CALLBACK_DATA_RU = "RU"

CALLBACK_DATA_GIVE_QUESTION = "give_question"
CALLBACK_DATA_ADD_ADVERTISEMENT = "give_advertisement"
CALLBACK_DATA_ADD_PHOTOS = "ADD_PHOTOS"

CALLBACK_DATA_ECONOMIC = "ECONOMIC"
CALLBACK_DATA_STANDARD = "STANDARD"
CALLBACK_DATA_PREMIUM = "PREMIUM"
CALLBACK_DATA_ELITE = "ELITE"
CALLBACK_DATA_EXCLUSIVE = "EXCLUSIVE"
CALLBACK_DATA_EXTREME = "EXTREME"

CALLBACK_DATA_CLICK = "CLICK"
CALLBACK_DATA_PAYME = "PAYME"
